In [1]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    'Country': ['France', 'Spain', 'Germany', 'Spain', 'Germany',
                'France', 'Spain', 'France', np.nan, 'France'],
    'Age': [25, 32, 28, 45, 36, 29, np.nan, 42, 55, 39],
    'Salary': [35000, 52000, 46000, 68000, np.nan,
               41000, 59000, 75000, 88000, 63000],
    'Purchased': ['Yes', 'No', 'Yes', 'No', 'Yes',
                  'No', 'Yes', 'No', 'Yes', 'No']
})

print("Original Data:")
print(df)

df['Country'] = df['Country'].fillna(df['Country'].mode()[0])

features = df.iloc[:, :-1].values
label = df.iloc[:, -1].values

from sklearn.impute import SimpleImputer

age = SimpleImputer(strategy="mean", missing_values=np.nan)
Salary = SimpleImputer(strategy="mean", missing_values=np.nan)

age.fit(features[:, [1]])
Salary.fit(features[:, [2]])

features[:, [1]] = age.transform(features[:, [1]])
features[:, [2]] = Salary.transform(features[:, [2]])

print("\nAfter Handling Missing Values:")
print(features)

from sklearn.preprocessing import OneHotEncoder

oh = OneHotEncoder(sparse_output=False)

Country = oh.fit_transform(features[:, [0]])

print("\nOne Hot Encoded Country:")
print(Country)

final_set = np.concatenate((Country, features[:, [1, 2]]), axis=1)

print("\nFinal Set:")
print(final_set)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

sc.fit(final_set)

feat_standard_scaler = sc.transform(final_set)

print("\nStandard Scaled Data:")
print(feat_standard_scaler)

from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler(feature_range=(0, 1))

mms.fit(final_set)

feat_minmax_scaler = mms.transform(final_set)

print("\nMin-Max Scaled Data:")
print(feat_minmax_scaler)

Original Data:
   Country   Age   Salary Purchased
0   France  25.0  35000.0       Yes
1    Spain  32.0  52000.0        No
2  Germany  28.0  46000.0       Yes
3    Spain  45.0  68000.0        No
4  Germany  36.0      NaN       Yes
5   France  29.0  41000.0        No
6    Spain   NaN  59000.0       Yes
7   France  42.0  75000.0        No
8      NaN  55.0  88000.0       Yes
9   France  39.0  63000.0        No

After Handling Missing Values:
[['France' 25.0 35000.0]
 ['Spain' 32.0 52000.0]
 ['Germany' 28.0 46000.0]
 ['Spain' 45.0 68000.0]
 ['Germany' 36.0 58555.555555555555]
 ['France' 29.0 41000.0]
 ['Spain' 36.77777777777778 59000.0]
 ['France' 42.0 75000.0]
 ['France' 55.0 88000.0]
 ['France' 39.0 63000.0]]

One Hot Encoded Country:
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]

Final Set:
[[1.0 0.0 0.0 25.0 35000.0]
 [0.0 0.0 1.0 32.0 52000.0]
 [0.0 1.0 0.0 28.0 46000.0]
 [0.0 0.0 1.0 45.0 68000.0]
 [0.0 1.0 0.